spring:
  application:
    name: financestocks
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    name: database
    driver-class-name: ${DATA_DRIVER:org.hsqldb.jdbc.JDBCDriver}
    url: ${DATA_URL:jdbc:hsqldb:file:~/db/datadb;shutdown=true}
    username: ${DATA_USENAME:sa}
    password: ${DATA_PASSWORD:}
    hikari:
      auto-commit: true
      connection-timeout: 3000
      idle-timeout: 5000
      keepalive-time: 1000
      maximum-pool-size: 5
      minimum-idle: 0
      max-lifetime: 5000